/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGidRouteImport } from './routes/groups.$gid'
import { Route as GroupsGidIndexRouteImport } from './routes/groups.$gid.index'
import { Route as GroupsGidTripsRouteImport } from './routes/groups.$gid.trips'
import { Route as GroupsGidMembersRouteImport } from './routes/groups.$gid.members'
import { Route as GroupsGidLeaderboardRouteImport } from './routes/groups.$gid.leaderboard'
import { Route as GroupsGidChatRouteImport } from './routes/groups.$gid.chat'
import { Route as GroupsGidAdminRouteImport } from './routes/groups.$gid.admin'
import { Route as GroupsGidTeeTimesIndexRouteImport } from './routes/groups.$gid.tee-times.index'
import { Route as GroupsGidTripsTidRouteImport } from './routes/groups.$gid.trips.$tid'
import { Route as GroupsGidTeeTimesTidRouteImport } from './routes/groups.$gid.tee-times.$tid'
import { Route as GroupsGidTeeTimesTidScorecardRouteImport } from './routes/groups.$gid.tee-times.$tid.scorecard'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGidRoute = GroupsGidRouteImport.update({
  id: '/groups/$gid',
  path: '/groups/$gid',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGidIndexRoute = GroupsGidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidTripsRoute = GroupsGidTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidMembersRoute = GroupsGidMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidLeaderboardRoute = GroupsGidLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidChatRoute = GroupsGidChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidAdminRoute = GroupsGidAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidTeeTimesIndexRoute = GroupsGidTeeTimesIndexRouteImport.update({
  id: '/tee-times/',
  path: '/tee-times/',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidTripsTidRoute = GroupsGidTripsTidRouteImport.update({
  id: '/$tid',
  path: '/$tid',
  getParentRoute: () => GroupsGidTripsRoute,
} as any)
const GroupsGidTeeTimesTidRoute = GroupsGidTeeTimesTidRouteImport.update({
  id: '/tee-times/$tid',
  path: '/tee-times/$tid',
  getParentRoute: () => GroupsGidRoute,
} as any)
const GroupsGidTeeTimesTidScorecardRoute =
  GroupsGidTeeTimesTidScorecardRouteImport.update({
    id: '/scorecard',
    path: '/scorecard',
    getParentRoute: () => GroupsGidTeeTimesTidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/groups/$gid': typeof GroupsGidRouteWithChildren
  '/groups/$gid/admin': typeof GroupsGidAdminRoute
  '/groups/$gid/chat': typeof GroupsGidChatRoute
  '/groups/$gid/leaderboard': typeof GroupsGidLeaderboardRoute
  '/groups/$gid/members': typeof GroupsGidMembersRoute
  '/groups/$gid/trips': typeof GroupsGidTripsRouteWithChildren
  '/groups/$gid/': typeof GroupsGidIndexRoute
  '/groups/$gid/tee-times/$tid': typeof GroupsGidTeeTimesTidRouteWithChildren
  '/groups/$gid/trips/$tid': typeof GroupsGidTripsTidRoute
  '/groups/$gid/tee-times/': typeof GroupsGidTeeTimesIndexRoute
  '/groups/$gid/tee-times/$tid/scorecard': typeof GroupsGidTeeTimesTidScorecardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/groups/$gid/admin': typeof GroupsGidAdminRoute
  '/groups/$gid/chat': typeof GroupsGidChatRoute
  '/groups/$gid/leaderboard': typeof GroupsGidLeaderboardRoute
  '/groups/$gid/members': typeof GroupsGidMembersRoute
  '/groups/$gid/trips': typeof GroupsGidTripsRouteWithChildren
  '/groups/$gid': typeof GroupsGidIndexRoute
  '/groups/$gid/tee-times/$tid': typeof GroupsGidTeeTimesTidRouteWithChildren
  '/groups/$gid/trips/$tid': typeof GroupsGidTripsTidRoute
  '/groups/$gid/tee-times': typeof GroupsGidTeeTimesIndexRoute
  '/groups/$gid/tee-times/$tid/scorecard': typeof GroupsGidTeeTimesTidScorecardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/groups/$gid': typeof GroupsGidRouteWithChildren
  '/groups/$gid/admin': typeof GroupsGidAdminRoute
  '/groups/$gid/chat': typeof GroupsGidChatRoute
  '/groups/$gid/leaderboard': typeof GroupsGidLeaderboardRoute
  '/groups/$gid/members': typeof GroupsGidMembersRoute
  '/groups/$gid/trips': typeof GroupsGidTripsRouteWithChildren
  '/groups/$gid/': typeof GroupsGidIndexRoute
  '/groups/$gid/tee-times/$tid': typeof GroupsGidTeeTimesTidRouteWithChildren
  '/groups/$gid/trips/$tid': typeof GroupsGidTripsTidRoute
  '/groups/$gid/tee-times/': typeof GroupsGidTeeTimesIndexRoute
  '/groups/$gid/tee-times/$tid/scorecard': typeof GroupsGidTeeTimesTidScorecardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/stats'
    | '/groups/$gid'
    | '/groups/$gid/admin'
    | '/groups/$gid/chat'
    | '/groups/$gid/leaderboard'
    | '/groups/$gid/members'
    | '/groups/$gid/trips'
    | '/groups/$gid/'
    | '/groups/$gid/tee-times/$tid'
    | '/groups/$gid/trips/$tid'
    | '/groups/$gid/tee-times/'
    | '/groups/$gid/tee-times/$tid/scorecard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/stats'
    | '/groups/$gid/admin'
    | '/groups/$gid/chat'
    | '/groups/$gid/leaderboard'
    | '/groups/$gid/members'
    | '/groups/$gid/trips'
    | '/groups/$gid'
    | '/groups/$gid/tee-times/$tid'
    | '/groups/$gid/trips/$tid'
    | '/groups/$gid/tee-times'
    | '/groups/$gid/tee-times/$tid/scorecard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/stats'
    | '/groups/$gid'
    | '/groups/$gid/admin'
    | '/groups/$gid/chat'
    | '/groups/$gid/leaderboard'
    | '/groups/$gid/members'
    | '/groups/$gid/trips'
    | '/groups/$gid/'
    | '/groups/$gid/tee-times/$tid'
    | '/groups/$gid/trips/$tid'
    | '/groups/$gid/tee-times/'
    | '/groups/$gid/tee-times/$tid/scorecard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  StatsRoute: typeof StatsRoute
  GroupsGidRoute: typeof GroupsGidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$gid': {
      id: '/groups/$gid'
      path: '/groups/$gid'
      fullPath: '/groups/$gid'
      preLoaderRoute: typeof GroupsGidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$gid/': {
      id: '/groups/$gid/'
      path: '/'
      fullPath: '/groups/$gid/'
      preLoaderRoute: typeof GroupsGidIndexRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/trips': {
      id: '/groups/$gid/trips'
      path: '/trips'
      fullPath: '/groups/$gid/trips'
      preLoaderRoute: typeof GroupsGidTripsRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/members': {
      id: '/groups/$gid/members'
      path: '/members'
      fullPath: '/groups/$gid/members'
      preLoaderRoute: typeof GroupsGidMembersRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/leaderboard': {
      id: '/groups/$gid/leaderboard'
      path: '/leaderboard'
      fullPath: '/groups/$gid/leaderboard'
      preLoaderRoute: typeof GroupsGidLeaderboardRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/chat': {
      id: '/groups/$gid/chat'
      path: '/chat'
      fullPath: '/groups/$gid/chat'
      preLoaderRoute: typeof GroupsGidChatRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/admin': {
      id: '/groups/$gid/admin'
      path: '/admin'
      fullPath: '/groups/$gid/admin'
      preLoaderRoute: typeof GroupsGidAdminRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/tee-times/': {
      id: '/groups/$gid/tee-times/'
      path: '/tee-times'
      fullPath: '/groups/$gid/tee-times/'
      preLoaderRoute: typeof GroupsGidTeeTimesIndexRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/trips/$tid': {
      id: '/groups/$gid/trips/$tid'
      path: '/$tid'
      fullPath: '/groups/$gid/trips/$tid'
      preLoaderRoute: typeof GroupsGidTripsTidRouteImport
      parentRoute: typeof GroupsGidTripsRoute
    }
    '/groups/$gid/tee-times/$tid': {
      id: '/groups/$gid/tee-times/$tid'
      path: '/tee-times/$tid'
      fullPath: '/groups/$gid/tee-times/$tid'
      preLoaderRoute: typeof GroupsGidTeeTimesTidRouteImport
      parentRoute: typeof GroupsGidRoute
    }
    '/groups/$gid/tee-times/$tid/scorecard': {
      id: '/groups/$gid/tee-times/$tid/scorecard'
      path: '/scorecard'
      fullPath: '/groups/$gid/tee-times/$tid/scorecard'
      preLoaderRoute: typeof GroupsGidTeeTimesTidScorecardRouteImport
      parentRoute: typeof GroupsGidTeeTimesTidRoute
    }
  }
}

interface GroupsGidTripsRouteChildren {
  GroupsGidTripsTidRoute: typeof GroupsGidTripsTidRoute
}

const GroupsGidTripsRouteChildren: GroupsGidTripsRouteChildren = {
  GroupsGidTripsTidRoute: GroupsGidTripsTidRoute,
}

const GroupsGidTripsRouteWithChildren = GroupsGidTripsRoute._addFileChildren(
  GroupsGidTripsRouteChildren,
)

interface GroupsGidTeeTimesTidRouteChildren {
  GroupsGidTeeTimesTidScorecardRoute: typeof GroupsGidTeeTimesTidScorecardRoute
}

const GroupsGidTeeTimesTidRouteChildren: GroupsGidTeeTimesTidRouteChildren = {
  GroupsGidTeeTimesTidScorecardRoute: GroupsGidTeeTimesTidScorecardRoute,
}

const GroupsGidTeeTimesTidRouteWithChildren =
  GroupsGidTeeTimesTidRoute._addFileChildren(GroupsGidTeeTimesTidRouteChildren)

interface GroupsGidRouteChildren {
  GroupsGidAdminRoute: typeof GroupsGidAdminRoute
  GroupsGidChatRoute: typeof GroupsGidChatRoute
  GroupsGidLeaderboardRoute: typeof GroupsGidLeaderboardRoute
  GroupsGidMembersRoute: typeof GroupsGidMembersRoute
  GroupsGidTripsRoute: typeof GroupsGidTripsRouteWithChildren
  GroupsGidIndexRoute: typeof GroupsGidIndexRoute
  GroupsGidTeeTimesTidRoute: typeof GroupsGidTeeTimesTidRouteWithChildren
  GroupsGidTeeTimesIndexRoute: typeof GroupsGidTeeTimesIndexRoute
}

const GroupsGidRouteChildren: GroupsGidRouteChildren = {
  GroupsGidAdminRoute: GroupsGidAdminRoute,
  GroupsGidChatRoute: GroupsGidChatRoute,
  GroupsGidLeaderboardRoute: GroupsGidLeaderboardRoute,
  GroupsGidMembersRoute: GroupsGidMembersRoute,
  GroupsGidTripsRoute: GroupsGidTripsRouteWithChildren,
  GroupsGidIndexRoute: GroupsGidIndexRoute,
  GroupsGidTeeTimesTidRoute: GroupsGidTeeTimesTidRouteWithChildren,
  GroupsGidTeeTimesIndexRoute: GroupsGidTeeTimesIndexRoute,
}

const GroupsGidRouteWithChildren = GroupsGidRoute._addFileChildren(
  GroupsGidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  StatsRoute: StatsRoute,
  GroupsGidRoute: GroupsGidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
